### ISSUE TITLE
Bodeplot für D-Glied wird nicht gerendert

### ISSUE THREAD

**Issue by iamkolja** [onecalfman/tubs-stuff#1]
`\DifAmp` zu `-\IntAmp` korrigieren
`\DifArg` zu `-\IntArg` korrigieren

**Comment by onecalfman** [comment]
Geschlossen mit [351c9ba](https://github.com/onecalfman/tubs-stuff/commit/351c9ba6000b5433cd5793bdd02a18a52292a82e)

Das pdf ist noch nicht neu gerendert.

**Comment by onecalfman** [comment]
@iamkolja Bei mir rendern die Plots grundsätzlich nicht mehr.
Hast du eine korrekte pdf version? Schick mir die sonst einfach per [Mail](mailto:jonas@walkling.email).
